name: Auto Pull Request

on:
  push:
    branches-ignore:
      - main # Exclude the main branch here
    paths-ignore:
      - '**.md' # Optionally, ignore certain file types or paths from triggering this workflow

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automated pull request'
          title: 'Automated Pull Request'
          body: 'This is an automated pull request triggered by a push to a non-main branch.'
          branch: ${{ github.event.ref }}
          base: 'main'






