name: Create Pull Request

on:
  push:
    branches:
      - '*'
    # Exclude main branch
    paths-ignore:
      - 'main/**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Current Branch Name
        id: get_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Create Pull Request
        run: |
          current_branch=${{ steps.get_branch.outputs.branch }}
          if [ "$current_branch" != "main" ]; then
            pr_title=$(gh pr create --base=main --head="$current_branch" --title "GitHub Actions: Automated Pull Request" --body "This pull request was automatically created by the GitHub Actions." --fill)
            echo "Automatic pull request has been created from $current_branch to main. Title: $pr_title. Thank you."
          fi




